from typing import Any, Optional, Union
import PCGCPP
import numpy.typing as npt

class PCG32:
    capsule: PCGCPP.RngCapsule

    def __init__(self, stream: Optional[int] = None, state: Optional[int] = None) -> None: ...
    def randint(self, size: int = 1, bound: int = 0) -> Union[npt.NDArray[Any], int]: ...
    def rand(self, size: int = 1) -> Union[npt.NDArray[Any], float]: ...
    def randn(self, size: int = 1) -> Union[npt.NDArray[Any], float]: ...
