apiVersion: v1
kind: ServiceAccount
metadata:
  name: dyme-module-workflow
  namespace: workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dyme-module-workflow
  namespace: workflows
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dyme-module-workflow
  namespace: workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dyme-module-workflow
subjects:
  - kind: ServiceAccount
    name: dyme-module-workflow
    namespace: workflows
